-- Create a simple schema to simulate a legacy application
CREATE TABLE CUSTOMERS (
    ID INT NOT NULL,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE ORDERS (
    ID INT NOT NULL,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    AMOUNT DECIMAL(10, 2),
    STATUS VARCHAR(20),
    PRIMARY KEY (ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

-- Seed some initial data
INSERT INTO CUSTOMERS (ID, NAME, EMAIL) VALUES (1, 'Alice Smith', 'alice@example.com');
INSERT INTO CUSTOMERS (ID, NAME, EMAIL) VALUES (2, 'Bob Jones', 'bob@example.com');

INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_DATE, AMOUNT, STATUS) VALUES (101, 1, '2023-01-01', 150.00, 'COMPLETED');
INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_DATE, AMOUNT, STATUS) VALUES (102, 2, '2023-01-05', 75.50, 'PENDING');
